### ISSUE TITLE
Python Turtle Arts

### ISSUE THREAD

**Issue by ayushmorbar** [Google-Developer-Student-Club-RJIT/DSA#2]
I wanna upload the arts using Python's Turtle module.

**Comment by infinity-lightning** [comment]
Assign me 🐁

**Comment by mr-palindrome** [comment]
Hello contributors!
This repo will only accept DSA-related codes. For more info please read [CODER_INSTRUCTIONS](https://github.com/Google-Developer-Student-Club-RJIT/DSA/blob/main/CODER_INSTRUCTIONS.md).
