### ISSUE TITLE
Row with max_1

### ISSUE THREAD

**Issue by adarsh4489** [Google-Developer-Student-Club-RJIT/DSA#4]
want to solve this algorithm in c++.
language:

 * [x] C++
 * [ ] C
  * [ ] JAVA
  * [ ] Python

Non-Code:

  * [x] Add readme
 * [ ]  Add images

problem link: https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1?page=2&status[]=unsolved&category[]=Arrays&category[]=Recursion&sortBy=submissions

to find row with max 1's

**Comment by Dhruv031003** [comment]
@adarsh4489 
Please also see #3 issue for an example of how to create an issue.
You can use "* [ ]" to create a checkbox.
Also comment in which language you will be solving it.
Solve it in your prefered language and raise PR.
Rest will be solved by others or you can if you want

**Comment by infinity-lightning** [comment]
assign me

**Comment by Dhruv031003** [comment]
@infinity-lightning 
He raised the issue to solve it.
If you want to solve an issue please raise one.
- Issue with member tag are raised to be solved by others.
- Example: 
![image](https://user-images.githubusercontent.com/91516121/197703900-f0693252-d922-4bd2-a03f-c8bea5278809.png)
