### ISSUE TITLE
create a program to find biggest number given among three number.

### ISSUE THREAD

**Issue by towardsinfinity1** [Google-Developer-Student-Club-RJIT/DSA#6]
you are organizing a exam the exam contin three part math, science and hindi after exam you have to 
creat ranking the ranking will be beased on the subject with the higest score write a program to find the higest
score among three subject */

**Comment by Dhruv031003** [comment]
@towardsinfinity1 
Please refer to #3

**Comment by towardsinfinity1** [comment]
ok sir

**Comment by Dhruv031003** [comment]
@towardsinfinity1 
Issue #3 is an example of how you should create an issue.
